#!/usr/bin/env bash
#Bash script to install nginx
sudo apt install nginx -y
sudo service nginx start
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i 's/^\(listen\s*80;\)/# \1\nlisten 80;/' /etc/nginx/sites-available/default

sudo kill -HUP "$(cat /var/run/nginx.pid)"
