#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
sed -i "s/102.132.97.35/8.8.8.8 facebook.com/g" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
